export { astroTemplate } from './astro'
export { honoTemplate } from './hono'
export { nextjsTemplate } from './nextjs'
export { nodeTemplate } from './node'
export { reactTemplate } from './react'
export { reactEslintTemplate } from './react-eslint'
export { solidTemplate } from './solid'
export { svelteTemplate } from './svelte'
export type { Template } from './types'
export { vanillaTemplate } from './vanilla-js'
export { vueTemplate } from './vue'
export { vueEslintTemplate } from './vue-eslint'
