export { nodeTemplate } from './node'
export { reactTemplate } from './react'
export type { Template } from './types'
export { vanillaTemplate } from './vanilla-js'
export { vueTemplate } from './vue'
